CREATE DATABASE IF NOT EXISTS tech;

USE tech;

CREATE TABLE IF NOT EXISTS funcionarios (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  cep VARCHAR(10) NOT NULL,
  endereco VARCHAR(255) NOT NULL,
  numero VARCHAR(10) NOT NULL,
  bairro VARCHAR(100) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(2) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY email_UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS cargos (
ID LONG auto_increment PRIMARY KEY,
NOME VARCHAR (90) NOT NULL,	
DESCRICAO VARCHAR (200) NOT NULL
);
